version: '3.7'

services:
  preview_proxy:
    build: 
      context: .
      
    restart: always

    environment: 
      - SSH_URL=${SSH_URL}
      - TLS_SERVERNAME=${TLS_SERVERNAME}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - DEBUG=1

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - 3000

    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:3000/healthz || exit 1
    #   interval: 10s
    #   retries: 4
    #   start_period: 20s
    #   timeout: 10s
