version: '3.7'

services:
  proxy:   
    build: .
    restart: always
    image: preview-proxy
    environment:
    - TUNNEL_SCHEME=http
    - TUNNEL_PORT=8030
    - SSH_HOST_KEY_FILE=./ssh/sample

    ports:
    - "8030:3000"
    - "2223:2222"